// The generated fixtures, and the create.mjs op that builds them.
//
// samples/fixture-{headings,clause,table-only,inline}.hwp are generated by
// scripts/build-fixtures.mjs and committed, because `scripts/` is not in the
// delivery allowlist — a generator-only fixture would be missing from every
// installed copy of the skill. Two things therefore need guarding:
//
//   1. the committed bytes are pinned by sha256, so a fixture cannot be
//      swapped or corrupted unnoticed;
//   2. the generator still produces the SAME DOCUMENT, compared semantically
//      (paragraph text, indent, control kinds/offsets, table cells) rather
//      than byte-for-byte. A byte comparison would go red on every engine bump
//      for reasons that have nothing to do with the fixture, and a test that
//      cries wolf every bump is a test nobody reads.
//
// When a fixture legitimately changes: edit build-fixtures.mjs, re-run it, and
// update FIXTURE_SHA256 from its output.

import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { loadDocument } from "../../src/lib/_bootstrap.mjs";
import { classifyParagraphControls, paragraphText } from "../../src/lib/doc_walk.mjs";
import { FIXTURE_DATA } from "../../scripts/build-fixtures.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const sample = (f) => join(ROOT, "samples", f);

const FIXTURE_SHA256 = {
  "fixture-headings.hwp": "818a905150f0a1294d15f0940797803fc2e8568bca5fa3e79595f921251207e3",
  "fixture-clause.hwp": "ace0325736a6cce1e566ecbd64c64405022b339b53b1fb1ab2da49c0e3eecb98",
  "fixture-table-only.hwp": "b08b6b66ede3b4ea5c3389b1bcde94dd46b930b206c1b776e4fcc03430884737",
  "fixture-inline.hwp": "99151d0c81552b80932235dba3ab0842e572778b4ee434bdcf9c5e93a96b0729",
};

test("fixtures: committed bytes match their pinned sha256", () => {
  for (const [name, want] of Object.entries(FIXTURE_SHA256)) {
    const got = createHash("sha256").update(readFileSync(sample(name))).digest("hex");
    assert.equal(got, want, `${name} drifted — re-run scripts/build-fixtures.mjs and update the pin`);
  }
});

test("fixtures: the generator still produces the same documents (semantic)", () => {
  const r = spawnSync(process.execPath, ["scripts/build-fixtures.mjs", "--check"], {
    cwd: ROOT,
    encoding: "utf8",
  });
  assert.equal(r.status, 0, `build-fixtures --check failed:\n${r.stdout}\n${r.stderr}`);
});

// ── what each fixture is supposed to contain ──────────────────────────────

test("fixture-headings: the TOC/heading twin pair is present and distinguishable", async () => {
  const doc = await loadDocument(sample("fixture-headings.hwp"));
  const texts = [];
  for (let p = 0; p < doc.getParagraphCount(0); p++) texts.push(paragraphText(doc, 0, p));

  const toc = texts.filter((t) => t.startsWith("1. 사업 개요") && t.includes("\t"));
  const heading = texts.filter((t) => t === "1. 사업 개요");
  assert.equal(toc.length, 1, "the table-of-contents twin must survive with its tab intact");
  assert.equal(heading.length, 1, "the heading twin must be present");
  // Same visible prefix, different line: this is the pair a number-only
  // detector gets exactly half right.
  assert.ok(toc[0].startsWith(heading[0]));
  assert.notEqual(toc[0], heading[0]);
});

test("fixture-headings: depth is carried by indent, not by style metadata", async () => {
  const doc = await loadDocument(sample("fixture-headings.hwp"));
  const props = (p) => JSON.parse(doc.getParaPropertiesAt(0, p));
  const byText = new Map();
  for (let p = 0; p < doc.getParagraphCount(0); p++) byText.set(paragraphText(doc, 0, p), p);

  const lvl0 = props(byText.get("□ 추진 배경")).marginLeft;
  const lvl1 = props(byText.get("○ 국내 현황")).marginLeft;
  const lvl2 = props(byText.get("- 시장 규모는 연 12% 성장하고 있다.")).marginLeft;
  assert.ok(lvl0 < lvl1 && lvl1 < lvl2, `indent must increase: ${lvl0} / ${lvl1} / ${lvl2}`);

  // And the metadata a Word-shaped detector would reach for is absent — this
  // is why the depth model has to be marker + indent.
  for (let p = 0; p < doc.getParagraphCount(0); p++) {
    const pr = props(p);
    assert.equal(pr.headType, "None", `paragraph ${p} unexpectedly has an outline headType`);
    assert.equal(pr.paraLevel, 0, `paragraph ${p} unexpectedly has a paraLevel`);
    assert.equal(pr.numberingId, 0, `paragraph ${p} unexpectedly has a numberingId`);
  }
});

test("fixture-headings: an indent never bleeds past the paragraph that declares it", async () => {
  // insertParagraph inherits the preceding paragraph's shape, so this is a real
  // failure mode of the generator, not a hypothetical one.
  const doc = await loadDocument(sample("fixture-headings.hwp"));
  for (let p = 0; p < doc.getParagraphCount(0); p++) {
    const text = paragraphText(doc, 0, p);
    const margin = JSON.parse(doc.getParaPropertiesAt(0, p)).marginLeft;
    const [, level] = FIXTURE_DATA.HEADING_LINES[p];
    if (level === 0) {
      assert.equal(margin, 0, `paragraph ${p} (${JSON.stringify(text)}) should be flush left`);
    } else {
      assert.ok(margin > 0, `paragraph ${p} (${JSON.stringify(text)}) should be indented`);
    }
  }
});

test("fixture-clause: 제N장/제N조 headings are INLINE with their body text", async () => {
  const doc = await loadDocument(sample("fixture-clause.hwp"));
  const texts = [];
  for (let p = 0; p < doc.getParagraphCount(0); p++) texts.push(paragraphText(doc, 0, p));
  const clause1 = texts.find((t) => t.startsWith("제1조"));
  assert.ok(clause1, "제1조 must be present");
  assert.ok(
    clause1.length > "제1조(목적)".length + 10,
    "the clause heading must share its paragraph with body text — that is the whole point",
  );
  assert.ok(texts.some((t) => t === "제1장 총칙"), "제N장 headings stand alone");
  // A cross-reference to 제3조 that is NOT at the start of a line.
  const xref = texts.find((t) => t.includes("제3조") && !t.startsWith("제3조"));
  assert.ok(xref, "the fixture must contain a mid-sentence 제N조 cross-reference");
});

test("fixture-table-only: every body paragraph is empty and the content is a table", async () => {
  const doc = await loadDocument(sample("fixture-table-only.hwp"));
  let tableCount = 0;
  for (let p = 0; p < doc.getParagraphCount(0); p++) {
    assert.equal(paragraphText(doc, 0, p), "", `paragraph ${p} must have no body text`);
    tableCount += classifyParagraphControls(doc, 0, p).filter((c) => c.kind === "table").length;
  }
  assert.equal(tableCount, 1, "exactly one table");
});

test("fixture-inline: two equations and a footnote at distinct known offsets", async () => {
  const doc = await loadDocument(sample("fixture-inline.hwp"));
  const controls = classifyParagraphControls(doc, 0, 0);

  const equations = controls.filter((c) => c.kind === "equation");
  assert.equal(equations.length, 2);
  assert.deepEqual(
    equations.map((e) => e.script),
    [FIXTURE_DATA.INLINE_EQ1, FIXTURE_DATA.INLINE_EQ2],
  );
  assert.deepEqual(
    equations.map((e) => e.offset),
    [FIXTURE_DATA.INLINE_OFFSETS.eq1, FIXTURE_DATA.INLINE_OFFSETS.eq2],
  );

  const footnotes = controls.filter((c) => c.kind === "footnote");
  assert.equal(footnotes.length, 1);
  assert.equal(footnotes[0].offset, FIXTURE_DATA.INLINE_OFFSETS.footnote);
  assert.ok(
    footnotes[0].texts.join("").includes(FIXTURE_DATA.INLINE_FOOTNOTE_TEXT),
    `footnote body not recovered: ${JSON.stringify(footnotes[0].texts)}`,
  );

  // The invisible pair is still there, and still first.
  assert.equal(controls[0].kind, "other");
  assert.equal(controls[1].kind, "other");

  // Zero-width: the paragraph text is exactly what was typed.
  assert.equal(paragraphText(doc, 0, 0), FIXTURE_DATA.INLINE_TEXT);
});

// ── create.mjs apply_para_format (create.mjs's first test) ─────────────────

test("create.mjs: apply_para_format sets a paragraph's left indent and round-trips", async () => {
  const dir = mkdtempSync(join(tmpdir(), "hwp-create-"));
  try {
    const plan = join(dir, "plan.json");
    const out = join(dir, "out.hwp");
    writeFileSync(
      plan,
      JSON.stringify({
        steps: [
          { op: "insert_text", section: 0, para: 0, char: 0, text: "레벨 0" },
          { op: "insert_paragraph", section: 0, para: 1 },
          { op: "insert_text", section: 0, para: 1, char: 0, text: "레벨 1" },
          { op: "apply_para_format", section: 0, para: 1, props: { marginLeft: 2000, indent: 0 } },
        ],
      }),
    );
    const r = spawnSync(process.execPath, ["src/core/create.mjs", "--plan", plan, "--output", out], {
      cwd: ROOT,
      encoding: "utf8",
    });
    assert.equal(r.status, 0, `create.mjs failed: ${r.stderr}`);
    const res = JSON.parse(r.stdout);
    assert.equal(res.verified, true);
    assert.ok(res.applied.some((a) => a.op === "apply_para_format"));

    const doc = await loadDocument(out);
    assert.equal(JSON.parse(doc.getParaPropertiesAt(0, 0)).marginLeft, 0);
    assert.ok(
      JSON.parse(doc.getParaPropertiesAt(0, 1)).marginLeft > 0,
      "the indent must survive save→reload",
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("create.mjs: apply_para_format without a props object is a usage error", () => {
  const dir = mkdtempSync(join(tmpdir(), "hwp-create-"));
  try {
    const plan = join(dir, "plan.json");
    writeFileSync(
      plan,
      JSON.stringify({
        steps: [
          { op: "insert_text", section: 0, para: 0, char: 0, text: "x" },
          { op: "apply_para_format", section: 0, para: 0, props: "marginLeft=2000" },
        ],
      }),
    );
    const r = spawnSync(
      process.execPath,
      ["src/core/create.mjs", "--plan", plan, "--output", join(dir, "out.hwp")],
      { cwd: ROOT, encoding: "utf8" },
    );
    // The engine accepts almost anything and reports {"ok":true}, so a typo'd
    // plan would otherwise be reported as applied while doing nothing.
    assert.equal(r.status, 2, `expected USAGE(2), got ${r.status}: ${r.stderr}`);
    assert.match(r.stderr, /props/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("create.mjs: an unknown op is still a usage error", () => {
  const dir = mkdtempSync(join(tmpdir(), "hwp-create-"));
  try {
    const plan = join(dir, "plan.json");
    writeFileSync(plan, JSON.stringify({ steps: [{ op: "teleport" }] }));
    const r = spawnSync(
      process.execPath,
      ["src/core/create.mjs", "--plan", plan, "--output", join(dir, "out.hwp")],
      { cwd: ROOT, encoding: "utf8" },
    );
    assert.equal(r.status, 2);
    assert.match(r.stderr, /unknown op/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
